In [2]:
import numpy as np

k = 6

points = np.random.random(size=(4*k,3))
centers = np.random.random(size=(k,3))
print(points)

dist = np.array([[np.linalg.norm(a-b) for b in centers] for a in points])
min_dist = np.array([a.argmin() for a in dist])
print(dist)
print(min_dist)

clusters = [points[min_dist == i] for i in range(k)]
for a in clusters:
  print(a)

[[0.40008973 0.84474449 0.86271395]
 [0.15921609 0.33597401 0.69517357]
 [0.70961316 0.60771056 0.0519755 ]
 [0.8651898  0.66871541 0.24729255]
 [0.51364303 0.80498181 0.46079814]
 [0.53838281 0.57372811 0.31440202]
 [0.38893933 0.31300694 0.51580318]
 [0.36292016 0.2144713  0.67329373]
 [0.0462098  0.02344852 0.06238978]
 [0.62890975 0.73865677 0.30363771]
 [0.09772469 0.83980647 0.39511496]
 [0.74969349 0.61606205 0.47887869]
 [0.63232982 0.540857   0.90460829]
 [0.46497342 0.16326436 0.32554774]
 [0.37821852 0.86395411 0.33287183]
 [0.03073037 0.69223063 0.8661788 ]
 [0.92343073 0.99624819 0.75882271]
 [0.89672561 0.51828687 0.02568065]
 [0.28650572 0.80043795 0.71428807]
 [0.16851523 0.7494634  0.75994395]
 [0.75732831 0.76715458 0.99253372]
 [0.10658015 0.96856674 0.3424945 ]
 [0.94712968 0.41486745 0.07680917]
 [0.55813697 0.43564999 0.73506958]]
[[0.59804384 0.70977852 0.35633305 0.4107159  0.8430113  0.86017509]
 [0.55495147 0.65730593 0.28880132 0.34564629 1.03469387 0.7171869