In [36]:
import numpy as np

k = 3

points = np.random.random(size=(4*k,3))
centers = np.random.random(size=(k,3))
print(centers)

dist = np.array([[np.linalg.norm(a-b) for b in centers] for a in points])
cluster = np.array([a.argmin() for a in dist])

means = np.array([np.mean(points[cluster == i], axis=0) for i in range(k)])
print(means)

errors = np.sum([np.sum([np.linalg.norm(a-b)**2 for b in points[cluster == i]]) for a, i in zip(means, range(k))])
print(errors)

[[0.4662225  0.49109828 0.21715877]
 [0.2216715  0.23228762 0.9741501 ]
 [0.33401404 0.56849879 0.9874614 ]]
[[0.609326   0.28484167 0.28201189]
 [0.16268935 0.273969   0.84441073]
 [0.54608097 0.69409482 0.72467681]]
1.52421390729639
