In [8]:
import numpy as np

k = 6

points = np.random.random(size=(4*k,3))
centers = np.random.random(size=(k,3))
print(centers)

dist = np.array([[np.linalg.norm(a-b) for b in centers] for a in points])
min_dist = np.array([a.argmin() for a in dist])
print(min_dist)

clusters = [points[min_dist == i] for i in range(k)]
means = np.array([np.mean(cluster, axis=0) for cluster in clusters])
print(means)

[[0.24825228 0.47517108 0.39435133]
 [0.09835118 0.05097567 0.06881328]
 [0.42553719 0.77152318 0.4670897 ]
 [0.08618042 0.75927406 0.97827304]
 [0.85319889 0.75921446 0.96556255]
 [0.59704298 0.29996855 0.44687676]]
[1 5 5 3 2 2 5 5 1 4 5 2 4 2 2 3 2 4 5 4 5 0 3 2]
[[0.08984087 0.0770878  0.52883259]
 [0.39294478 0.1589502  0.0906186 ]
 [0.56407572 0.81461665 0.31386568]
 [0.13637336 0.7593238  0.83239505]
 [0.72773731 0.67314517 0.84978217]
 [0.78506897 0.24609017 0.32285238]]
